server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: application
          uri: http://localhost:8082
          predicates:
            - Path=/applications/**, 
        - id: process1
          uri: http://localhost:8083
          predicates:
            - Path=/investigations/**, /processings/**, 
        - id: analysis1
          uri: http://localhost:8084
          predicates:
            - Path=/analysis1s/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: application
          uri: http://application:8080
          predicates:
            - Path=/applications/**, 
        - id: process1
          uri: http://process1:8080
          predicates:
            - Path=/investigations/**, /processings/**, 
        - id: analysis1
          uri: http://analysis1:8080
          predicates:
            - Path=/analysis1s/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
