---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: username/application:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: process1
  labels:
    app: process1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process1
  template:
    metadata:
      labels:
        app: process1
    spec:
      containers:
        - name: process1
          image: username/process1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis1
  labels:
    app: analysis1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis1
  template:
    metadata:
      labels:
        app: analysis1
    spec:
      containers:
        - name: analysis1
          image: username/analysis1:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: application


---


apiVersion: v1
kind: Service
metadata:
  name: process1
  labels:
    app: process1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: process1


---


apiVersion: v1
kind: Service
metadata:
  name: analysis1
  labels:
    app: analysis1
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: analysis1

